-- PostGIS database schema for the Benelux electronic music festival project.
-- Target DBMS: PostgreSQL + PostGIS
-- Spatial reference: EPSG:3035 (ETRS89-extended / LAEA Europe), meters.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DROP TABLE IF EXISTS site_evaluations CASCADE;
DROP TABLE IF EXISTS noise_sensitive_facilities CASCADE;
DROP TABLE IF EXISTS ecological_protected_areas CASCADE;
DROP TABLE IF EXISTS population_grids CASCADE;
DROP TABLE IF EXISTS transport_hubs CASCADE;
DROP TABLE IF EXISTS candidate_sites CASCADE;
DROP TABLE IF EXISTS ticket_price_offers CASCADE;
DROP TABLE IF EXISTS ticket_types CASCADE;
DROP TABLE IF EXISTS performance_artists CASCADE;
DROP TABLE IF EXISTS performances CASCADE;
DROP TABLE IF EXISTS artist_genres CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS stages CASCADE;
DROP TABLE IF EXISTS festival_editions CASCADE;
DROP TABLE IF EXISTS venues CASCADE;
DROP TABLE IF EXISTS festivals CASCADE;
DROP TABLE IF EXISTS organizers CASCADE;

CREATE TABLE organizers (
    organizer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL UNIQUE,
    country varchar(80),
    website text
);

CREATE TABLE festivals (
    festival_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id integer NOT NULL REFERENCES organizers(organizer_id),
    name varchar(120) NOT NULL UNIQUE,
    founded_year integer CHECK (founded_year BETWEEN 1900 AND 2100),
    home_country varchar(80) NOT NULL,
    website text
);

CREATE TABLE venues (
    venue_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    city varchar(100) NOT NULL,
    country varchar(80) NOT NULL,
    area_sqm numeric(14,2) CHECK (area_sqm IS NULL OR area_sqm > 0),
    data_source text,
    geom_polygon geometry(MultiPolygon, 3035),
    geom_point geometry(Point, 3035) NOT NULL,
    CONSTRAINT chk_venues_geom_polygon_valid
        CHECK (geom_polygon IS NULL OR (ST_IsValid(geom_polygon) AND ST_SRID(geom_polygon) = 3035)),
    CONSTRAINT chk_venues_geom_point_valid
        CHECK (ST_IsValid(geom_point) AND ST_SRID(geom_point) = 3035)
);

CREATE TABLE festival_editions (
    edition_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    festival_id integer NOT NULL REFERENCES festivals(festival_id),
    venue_id integer NOT NULL REFERENCES venues(venue_id),
    year integer NOT NULL CHECK (year BETWEEN 1990 AND 2100),
    start_date date NOT NULL,
    end_date date NOT NULL,
    expected_attendance integer CHECK (expected_attendance > 0),
    attendance_note text,
    CONSTRAINT chk_edition_dates CHECK (end_date >= start_date),
    CONSTRAINT uq_festival_edition UNIQUE (festival_id, year, start_date)
);

CREATE TABLE stages (
    stage_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id integer NOT NULL REFERENCES festival_editions(edition_id) ON DELETE CASCADE,
    name varchar(120) NOT NULL,
    capacity integer CHECK (capacity IS NULL OR capacity > 0),
    geom_point geometry(Point, 3035),
    CONSTRAINT uq_stage_per_edition UNIQUE (edition_id, name),
    CONSTRAINT chk_stages_geom_valid
        CHECK (geom_point IS NULL OR (ST_IsValid(geom_point) AND ST_SRID(geom_point) = 3035))
);

CREATE TABLE artists (
    artist_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL UNIQUE,
    country varchar(80)
);

CREATE TABLE genres (
    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(80) NOT NULL UNIQUE
);

CREATE TABLE artist_genres (
    artist_id integer NOT NULL REFERENCES artists(artist_id) ON DELETE CASCADE,
    genre_id integer NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
    PRIMARY KEY (artist_id, genre_id)
);

CREATE TABLE performances (
    performance_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_id integer NOT NULL REFERENCES stages(stage_id) ON DELETE CASCADE,
    official_performance_id varchar(120),
    performance_name varchar(240),
    start_time timestamp NOT NULL,
    end_time timestamp NOT NULL,
    estimated_crowd integer CHECK (estimated_crowd IS NULL OR estimated_crowd >= 0),
    CONSTRAINT chk_performance_time CHECK (end_time > start_time),
    CONSTRAINT uq_performance_official_id UNIQUE (stage_id, official_performance_id),
    CONSTRAINT uq_performance_block UNIQUE (stage_id, start_time, end_time, performance_name)
);

CREATE TABLE performance_artists (
    performance_id integer NOT NULL REFERENCES performances(performance_id) ON DELETE CASCADE,
    artist_id integer NOT NULL REFERENCES artists(artist_id),
    artist_order integer NOT NULL DEFAULT 1 CHECK (artist_order > 0),
    role varchar(40) NOT NULL DEFAULT 'primary',
    PRIMARY KEY (performance_id, artist_id)
);

CREATE TABLE ticket_types (
    ticket_type_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id integer NOT NULL REFERENCES festival_editions(edition_id) ON DELETE CASCADE,
    name varchar(120) NOT NULL,
    price_eur numeric(10,2) NOT NULL CHECK (price_eur >= 0),
    quota integer NOT NULL CHECK (quota > 0),
    is_simulated boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_ticket_type_per_edition UNIQUE (edition_id, name)
);

CREATE TABLE ticket_price_offers (
    offer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_type_id integer NOT NULL REFERENCES ticket_types(ticket_type_id) ON DELETE CASCADE,
    sale_category varchar(120) NOT NULL,
    price_eur numeric(10,2) NOT NULL CHECK (price_eur >= 0),
    currency char(3) NOT NULL DEFAULT 'EUR',
    price_status varchar(80),
    official_price_id varchar(120),
    source_url text,
    capture_timestamp varchar(20),
    confidence varchar(80) NOT NULL DEFAULT 'unknown',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ticket_price_offer UNIQUE (ticket_type_id, sale_category, official_price_id)
);

CREATE TABLE candidate_sites (
    site_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    source_osm_id varchar(80),
    terrain_type varchar(80) NOT NULL,
    area_sqm numeric(14,2) NOT NULL,
    daily_cost numeric(12,2) CHECK (daily_cost IS NULL OR daily_cost >= 0),
    data_source text,
    is_manual_sample boolean NOT NULL DEFAULT true,
    geom_polygon geometry(MultiPolygon, 3035) NOT NULL,
    CONSTRAINT chk_site_area CHECK (area_sqm >= 50000),
    CONSTRAINT chk_site_geom_valid CHECK (ST_IsValid(geom_polygon) AND ST_SRID(geom_polygon) = 3035)
);

CREATE TABLE site_evaluations (
    evaluation_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id integer NOT NULL REFERENCES candidate_sites(site_id) ON DELETE CASCADE,
    evaluated_at date NOT NULL DEFAULT CURRENT_DATE,
    airport_score numeric(5,2) NOT NULL CHECK (airport_score BETWEEN 0 AND 100),
    population_score numeric(5,2) NOT NULL CHECK (population_score BETWEEN 0 AND 100),
    ecology_safety_score numeric(5,2) NOT NULL CHECK (ecology_safety_score BETWEEN 0 AND 100),
    noise_safety_score numeric(5,2) NOT NULL CHECK (noise_safety_score BETWEEN 0 AND 100),
    total_score numeric(5,2) NOT NULL CHECK (total_score BETWEEN 0 AND 100),
    method_note text,
    CONSTRAINT uq_site_evaluation_date UNIQUE (site_id, evaluated_at)
);

CREATE TABLE transport_hubs (
    hub_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    hub_type varchar(40) NOT NULL,
    city varchar(100),
    country varchar(80),
    daily_capacity integer CHECK (daily_capacity IS NULL OR daily_capacity > 0),
    data_source text,
    geom_point geometry(Point, 3035) NOT NULL,
    CONSTRAINT chk_hub_type CHECK (hub_type IN ('airport', 'train_station', 'metro_station', 'bus_terminal')),
    CONSTRAINT chk_transport_hubs_geom_valid CHECK (ST_IsValid(geom_point) AND ST_SRID(geom_point) = 3035)
);

CREATE TABLE population_grids (
    grid_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    population integer NOT NULL CHECK (population >= 0),
    edm_fan_index numeric(4,3) NOT NULL CHECK (edm_fan_index BETWEEN 0 AND 1),
    data_source text,
    is_synthetic_sample boolean NOT NULL DEFAULT true,
    geom_polygon geometry(Polygon, 3035) NOT NULL,
    CONSTRAINT chk_population_grids_geom_valid CHECK (ST_IsValid(geom_polygon) AND ST_SRID(geom_polygon) = 3035)
);

CREATE TABLE ecological_protected_areas (
    reserve_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(180) NOT NULL,
    protect_type varchar(80) NOT NULL,
    data_source text,
    geom_polygon geometry(MultiPolygon, 3035) NOT NULL,
    CONSTRAINT chk_protected_areas_geom_valid CHECK (ST_IsValid(geom_polygon) AND ST_SRID(geom_polygon) = 3035)
);

CREATE TABLE noise_sensitive_facilities (
    facility_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(180) NOT NULL,
    facility_type varchar(40) NOT NULL,
    sensitivity_level integer NOT NULL CHECK (sensitivity_level BETWEEN 1 AND 5),
    city varchar(100),
    country varchar(80),
    data_source text,
    geom_point geometry(Point, 3035) NOT NULL,
    CONSTRAINT chk_facility_type CHECK (facility_type IN ('hospital', 'school', 'residential', 'elderly_care')),
    CONSTRAINT chk_noise_sensitive_geom_valid CHECK (ST_IsValid(geom_point) AND ST_SRID(geom_point) = 3035)
);

CREATE INDEX idx_festivals_organizer_id ON festivals(organizer_id);
CREATE INDEX idx_editions_festival_id ON festival_editions(festival_id);
CREATE INDEX idx_editions_venue_id ON festival_editions(venue_id);
CREATE INDEX idx_stages_edition_id ON stages(edition_id);
CREATE INDEX idx_performances_stage_id ON performances(stage_id);
CREATE INDEX idx_performances_start_time ON performances(start_time);
CREATE INDEX idx_performances_business_day ON performances(((start_time - interval '5 hours')::date));
CREATE INDEX idx_performance_artists_artist_id ON performance_artists(artist_id);
CREATE INDEX idx_genres_name_trgm ON genres USING gin (name gin_trgm_ops);
CREATE INDEX idx_ticket_types_edition_id ON ticket_types(edition_id);
CREATE INDEX idx_ticket_price_offers_ticket_type_id ON ticket_price_offers(ticket_type_id);
CREATE INDEX idx_ticket_price_offers_sale_category ON ticket_price_offers(sale_category);
CREATE INDEX idx_site_evaluations_site_id ON site_evaluations(site_id);

CREATE INDEX idx_venues_geom_polygon ON venues USING gist (geom_polygon);
CREATE INDEX idx_venues_geom_point ON venues USING gist (geom_point);
CREATE INDEX idx_stages_geom_point ON stages USING gist (geom_point);
CREATE INDEX idx_candidate_sites_geom ON candidate_sites USING gist (geom_polygon);
CREATE INDEX idx_transport_hubs_geom ON transport_hubs USING gist (geom_point);
CREATE INDEX idx_population_grids_geom ON population_grids USING gist (geom_polygon);
CREATE INDEX idx_protected_areas_geom ON ecological_protected_areas USING gist (geom_polygon);
CREATE INDEX idx_noise_sensitive_geom ON noise_sensitive_facilities USING gist (geom_point);
