-- Import cleaned Tomorrowland 2025 official lineup/timetable captures into staging tables.
-- Source CSVs are generated by scripts/parse_tomorrowland_lineup_capture.py.

DROP TABLE IF EXISTS stg_tomorrowland_2025_performances;
DROP TABLE IF EXISTS stg_tomorrowland_2025_artists;
DROP TABLE IF EXISTS stg_tomorrowland_2025_stages;
DROP TABLE IF EXISTS stg_tomorrowland_2025_weekends;

CREATE TABLE stg_tomorrowland_2025_weekends (
    festival text NOT NULL,
    edition_year integer NOT NULL,
    weekend_code text NOT NULL,
    start_datetime_local text NOT NULL,
    end_datetime_local text NOT NULL,
    with_timetable boolean,
    source_file text,
    capture_timestamp text,
    source_url_hint text,
    imported_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (festival, edition_year, weekend_code)
);

CREATE TABLE stg_tomorrowland_2025_stages (
    festival text NOT NULL,
    edition_year integer NOT NULL,
    official_stage_id text NOT NULL,
    stage_name text NOT NULL,
    hosts_by_date text,
    source_file text,
    capture_timestamp text,
    source_url_hint text,
    imported_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (festival, edition_year, official_stage_id)
);

CREATE TABLE stg_tomorrowland_2025_artists (
    festival text NOT NULL,
    edition_year integer NOT NULL,
    official_artist_id text NOT NULL,
    artist_name text NOT NULL,
    image_url text,
    website text,
    instagram text,
    spotify text,
    source_file text,
    capture_timestamp text,
    source_url_hint text,
    imported_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (festival, edition_year, official_artist_id)
);

CREATE TABLE stg_tomorrowland_2025_performances (
    festival text NOT NULL,
    edition_year integer NOT NULL,
    weekend_code text NOT NULL,
    official_performance_id text NOT NULL,
    performance_name text NOT NULL,
    official_stage_id text NOT NULL,
    stage_name text NOT NULL,
    official_artist_ids text,
    artist_names text,
    performance_date date NOT NULL,
    day_name text,
    start_time_local text NOT NULL,
    end_time_local text NOT NULL,
    source_file text,
    capture_timestamp text,
    source_url_hint text,
    imported_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (festival, edition_year, official_performance_id)
);

\copy stg_tomorrowland_2025_weekends (festival, edition_year, weekend_code, start_datetime_local, end_datetime_local, with_timetable, source_file, capture_timestamp, source_url_hint) FROM 'data/processed/tomorrowland_2025_weekends_official.csv' WITH CSV HEADER ENCODING 'UTF8'
\copy stg_tomorrowland_2025_stages (festival, edition_year, official_stage_id, stage_name, hosts_by_date, source_file, capture_timestamp, source_url_hint) FROM 'data/processed/tomorrowland_2025_stages_official.csv' WITH CSV HEADER ENCODING 'UTF8'
\copy stg_tomorrowland_2025_artists (festival, edition_year, official_artist_id, artist_name, image_url, website, instagram, spotify, source_file, capture_timestamp, source_url_hint) FROM 'data/processed/tomorrowland_2025_artists_official.csv' WITH CSV HEADER ENCODING 'UTF8'
\copy stg_tomorrowland_2025_performances (festival, edition_year, weekend_code, official_performance_id, performance_name, official_stage_id, stage_name, official_artist_ids, artist_names, performance_date, day_name, start_time_local, end_time_local, source_file, capture_timestamp, source_url_hint) FROM 'data/processed/tomorrowland_2025_performances_official.csv' WITH CSV HEADER ENCODING 'UTF8'

CREATE INDEX idx_stg_tl25_perf_time ON stg_tomorrowland_2025_performances (performance_date, stage_name);
CREATE INDEX idx_stg_tl25_perf_stage ON stg_tomorrowland_2025_performances (official_stage_id);
CREATE INDEX idx_stg_tl25_perf_artist_names ON stg_tomorrowland_2025_performances (artist_names);
