-- Import Tomorrowland 2025 official ticket prices captured from Wayback snapshots.
-- Source CSV is generated by scripts/parse_tomorrowland_ticket_prices_capture.py.
-- Prices are official page values; quotas remain unavailable from these pages.

DROP TABLE IF EXISTS stg_tomorrowland_2025_ticket_prices;

CREATE TABLE stg_tomorrowland_2025_ticket_prices (
    festival text,
    edition_year integer,
    ticket_name text,
    sale_category text,
    price_eur numeric(10,2),
    currency text,
    formatted_price text,
    price_status text,
    page_title text,
    page_url text,
    official_product_id text,
    official_price_id text,
    capture_timestamp text,
    source_file text,
    source_url_hint text,
    confidence text
);

\copy stg_tomorrowland_2025_ticket_prices (festival, edition_year, ticket_name, sale_category, price_eur, currency, formatted_price, price_status, page_title, page_url, official_product_id, official_price_id, capture_timestamp, source_file, source_url_hint, confidence) FROM 'data/processed/tomorrowland_2025_ticket_prices_official_wayback.csv' WITH CSV HEADER ENCODING 'UTF8'

CREATE INDEX idx_stg_tl25_ticket_prices_name ON stg_tomorrowland_2025_ticket_prices (ticket_name);
CREATE INDEX idx_stg_tl25_ticket_prices_sale ON stg_tomorrowland_2025_ticket_prices (sale_category);

SELECT
    ticket_name,
    sale_category,
    price_eur,
    currency,
    confidence
FROM stg_tomorrowland_2025_ticket_prices
ORDER BY ticket_name, sale_category;
