-- Promote Tomorrowland 2025 official Wayback ticket prices into normalized tables.
-- Prerequisite: sql/15_import_tomorrowland_2025_ticket_prices.sql has loaded
-- stg_tomorrowland_2025_ticket_prices.

BEGIN;

CREATE TABLE IF NOT EXISTS ticket_price_offers (
    offer_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_type_id integer NOT NULL REFERENCES ticket_types(ticket_type_id) ON DELETE CASCADE,
    sale_category varchar(120) NOT NULL,
    price_eur numeric(10,2) NOT NULL CHECK (price_eur >= 0),
    currency char(3) NOT NULL DEFAULT 'EUR',
    price_status varchar(80),
    official_price_id varchar(120),
    source_url text,
    capture_timestamp varchar(20),
    confidence varchar(80) NOT NULL DEFAULT 'unknown',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ticket_price_offer UNIQUE (ticket_type_id, sale_category, official_price_id)
);

CREATE INDEX IF NOT EXISTS idx_ticket_price_offers_ticket_type_id
    ON ticket_price_offers(ticket_type_id);
CREATE INDEX IF NOT EXISTS idx_ticket_price_offers_sale_category
    ON ticket_price_offers(sale_category);

WITH tl25 AS (
    SELECT fe.edition_id
    FROM festival_editions fe
    JOIN festivals f ON f.festival_id = fe.festival_id
    WHERE f.name = 'Tomorrowland'
      AND fe.year = 2025
)
INSERT INTO ticket_types (edition_id, name, price_eur, quota, is_simulated)
SELECT
    tl25.edition_id,
    stg.ticket_name,
    -- ticket_types keeps one representative price and a required quota for the
    -- legacy coursework schema. Official sale-stage prices live below in
    -- ticket_price_offers; quotas are not available from the official page.
    MIN(stg.price_eur) AS price_eur,
    1 AS quota,
    true AS is_simulated
FROM stg_tomorrowland_2025_ticket_prices stg
CROSS JOIN tl25
GROUP BY tl25.edition_id, stg.ticket_name
ON CONFLICT (edition_id, name) DO UPDATE
SET
    price_eur = EXCLUDED.price_eur;

INSERT INTO ticket_price_offers (
    ticket_type_id,
    sale_category,
    price_eur,
    currency,
    price_status,
    official_price_id,
    source_url,
    capture_timestamp,
    confidence
)
SELECT
    tt.ticket_type_id,
    stg.sale_category,
    stg.price_eur,
    stg.currency,
    stg.price_status,
    stg.official_price_id,
    stg.source_url_hint,
    stg.capture_timestamp,
    stg.confidence
FROM stg_tomorrowland_2025_ticket_prices stg
JOIN festivals f
  ON f.name = stg.festival
JOIN festival_editions fe
  ON fe.festival_id = f.festival_id
 AND fe.year = stg.edition_year
JOIN ticket_types tt
  ON tt.edition_id = fe.edition_id
 AND tt.name = stg.ticket_name
ON CONFLICT (ticket_type_id, sale_category, official_price_id) DO UPDATE
SET
    price_eur = EXCLUDED.price_eur,
    currency = EXCLUDED.currency,
    price_status = EXCLUDED.price_status,
    source_url = EXCLUDED.source_url,
    capture_timestamp = EXCLUDED.capture_timestamp,
    confidence = EXCLUDED.confidence;

COMMIT;

SELECT
    f.name AS festival,
    fe.year,
    tt.name AS ticket_name,
    tpo.sale_category,
    tpo.price_eur,
    tpo.currency,
    tpo.confidence
FROM ticket_price_offers tpo
JOIN ticket_types tt ON tt.ticket_type_id = tpo.ticket_type_id
JOIN festival_editions fe ON fe.edition_id = tt.edition_id
JOIN festivals f ON f.festival_id = fe.festival_id
WHERE f.name = 'Tomorrowland'
  AND fe.year = 2025
ORDER BY tt.name, tpo.sale_category;
