-- Import network-enriched genre labels for Tomorrowland 2025 artists only.
-- Source CSV is generated by scripts/enrich_tomorrowland_artist_genres.py.

BEGIN;

DROP TABLE IF EXISTS stg_tomorrowland_2025_artist_genres_enriched;

CREATE TABLE stg_tomorrowland_2025_artist_genres_enriched (
    artist_name varchar(160) NOT NULL,
    genre_name varchar(120) NOT NULL,
    source varchar(120) NOT NULL,
    confidence varchar(80) NOT NULL,
    source_url text
);

\copy stg_tomorrowland_2025_artist_genres_enriched (artist_name, genre_name, source, confidence, source_url) FROM 'data/processed/tomorrowland_2025_artist_genres_enriched.csv' WITH CSV HEADER ENCODING 'UTF8'

CREATE INDEX idx_stg_tl25_artist_genres_artist
    ON stg_tomorrowland_2025_artist_genres_enriched (artist_name);
CREATE INDEX idx_stg_tl25_artist_genres_genre
    ON stg_tomorrowland_2025_artist_genres_enriched (genre_name);

INSERT INTO genres (name)
SELECT DISTINCT trim(genre_name)
FROM stg_tomorrowland_2025_artist_genres_enriched
WHERE trim(genre_name) <> ''
ON CONFLICT (name) DO NOTHING;

WITH tl25_artists AS (
    SELECT DISTINCT a.artist_id, a.name
    FROM artists a
    JOIN performance_artists pa ON pa.artist_id = a.artist_id
    JOIN performances p ON p.performance_id = pa.performance_id
    JOIN stages s ON s.stage_id = p.stage_id
    JOIN festival_editions fe ON fe.edition_id = s.edition_id
    JOIN festivals f ON f.festival_id = fe.festival_id
    WHERE f.name = 'Tomorrowland'
      AND fe.year = 2025
)
INSERT INTO artist_genres (artist_id, genre_id)
SELECT DISTINCT
    a.artist_id,
    g.genre_id
FROM stg_tomorrowland_2025_artist_genres_enriched stg
JOIN tl25_artists a
  ON lower(a.name) = lower(trim(stg.artist_name))
JOIN genres g
  ON g.name = trim(stg.genre_name)
WHERE trim(stg.genre_name) <> ''
ON CONFLICT (artist_id, genre_id) DO NOTHING;

COMMIT;

SELECT
    COUNT(DISTINCT a.artist_id) AS tomorrowland_artists_with_genre,
    COUNT(*) AS tomorrowland_artist_genre_links
FROM artist_genres ag
JOIN artists a ON a.artist_id = ag.artist_id
WHERE EXISTS (
    SELECT 1
    FROM performance_artists pa
    JOIN performances p ON p.performance_id = pa.performance_id
    JOIN stages s ON s.stage_id = p.stage_id
    JOIN festival_editions fe ON fe.edition_id = s.edition_id
    JOIN festivals f ON f.festival_id = fe.festival_id
    WHERE pa.artist_id = a.artist_id
      AND f.name = 'Tomorrowland'
      AND fe.year = 2025
);

SELECT
    g.name AS genre_name,
    COUNT(DISTINCT ag.artist_id) AS artist_count
FROM artist_genres ag
JOIN genres g ON g.genre_id = ag.genre_id
WHERE EXISTS (
    SELECT 1
    FROM performance_artists pa
    JOIN performances p ON p.performance_id = pa.performance_id
    JOIN stages s ON s.stage_id = p.stage_id
    JOIN festival_editions fe ON fe.edition_id = s.edition_id
    JOIN festivals f ON f.festival_id = fe.festival_id
    WHERE pa.artist_id = ag.artist_id
      AND f.name = 'Tomorrowland'
      AND fe.year = 2025
)
GROUP BY g.name
ORDER BY artist_count DESC, g.name
LIMIT 25;
